[phases.build]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python scripts/migrate_and_start.py"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"